export type {
  EnrichedMusixmatchMetadata,
  MatchCandidate,
  MetadataType,
  MusicAdapter,
  MusicParser,
  PlatformId,
  ResolveOptions,
  ResolverConfig,
  ResolveResult,
  ResolvedLink,
  ResolverTrackMetadata,
  ScoreBreakdown,
  TrackMetadata,
} from "@repo/types";
